server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shirodemo?serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  configuration:
    lazy-loading-enabled: true
    cache-enabled: true
    aggressive-lazy-loading: true
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    com.example.dao: debug